export const ActionsTypes= {
    SET_PROPERTIES:"SET_PROPERTIES",
  SET_USER: "SET_USER",
    SELECTED_PROPERTIES:"SELECT_PROPERTIES",
  REMOVE_PROPERTIES: "REMOVE_PROPERTIES",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",

}

